spring.application.name=constru_app
spring.datasource.url=jdbc:mysql://localhost/constru_app
spring.datasource.username=root
spring.datasource.password=jdproot123456
//spring.datasource.password=Ap.**2697_
spring.jpa.open-in-view=false

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=update
server.port=7010
